/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Nat;
export const Units = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rupees = IDL.Nat;
export const BillEstimate = IDL.Record({
  'totalCost' : Rupees,
  'unitsConsumed' : Units,
  'unitCost' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'consumerNumber' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserId = IDL.Principal;
export const ConsumptionRecord = IDL.Record({
  'date' : Timestamp,
  'user' : UserId,
  'unitsConsumed' : Units,
  'timestamp' : Timestamp,
});
export const SlabBreakdown = IDL.Record({
  'cost' : Rupees,
  'name' : IDL.Text,
  'units' : Units,
  'perUnitCost' : IDL.Nat,
});
export const BillDetails = IDL.Record({
  'fixedCharges' : Rupees,
  'totalCost' : Rupees,
  'totalUnitsConsumed' : Units,
  'slabCosts' : IDL.Vec(SlabBreakdown),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addConsumptionRecord' : IDL.Func([Timestamp, Units], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateBillEstimate' : IDL.Func(
      [Units, IDL.Bool],
      [BillEstimate],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsumptionRecordsByUser' : IDL.Func(
      [UserId],
      [IDL.Vec(ConsumptionRecord)],
      ['query'],
    ),
  'getDetailedBillEstimate' : IDL.Func(
      [Units, IDL.Bool],
      [BillDetails],
      ['query'],
    ),
  'getTotalUnitsConsumed' : IDL.Func([UserId], [Units], ['query']),
  'getUserConsumptionRecords' : IDL.Func(
      [],
      [IDL.Vec(ConsumptionRecord)],
      ['query'],
    ),
  'getUserConsumptionSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'records' : IDL.Vec(ConsumptionRecord),
          'totalUnits' : Units,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedTestConsumptionData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Nat;
  const Units = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rupees = IDL.Nat;
  const BillEstimate = IDL.Record({
    'totalCost' : Rupees,
    'unitsConsumed' : Units,
    'unitCost' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'consumerNumber' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const ConsumptionRecord = IDL.Record({
    'date' : Timestamp,
    'user' : UserId,
    'unitsConsumed' : Units,
    'timestamp' : Timestamp,
  });
  const SlabBreakdown = IDL.Record({
    'cost' : Rupees,
    'name' : IDL.Text,
    'units' : Units,
    'perUnitCost' : IDL.Nat,
  });
  const BillDetails = IDL.Record({
    'fixedCharges' : Rupees,
    'totalCost' : Rupees,
    'totalUnitsConsumed' : Units,
    'slabCosts' : IDL.Vec(SlabBreakdown),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addConsumptionRecord' : IDL.Func([Timestamp, Units], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateBillEstimate' : IDL.Func(
        [Units, IDL.Bool],
        [BillEstimate],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsumptionRecordsByUser' : IDL.Func(
        [UserId],
        [IDL.Vec(ConsumptionRecord)],
        ['query'],
      ),
    'getDetailedBillEstimate' : IDL.Func(
        [Units, IDL.Bool],
        [BillDetails],
        ['query'],
      ),
    'getTotalUnitsConsumed' : IDL.Func([UserId], [Units], ['query']),
    'getUserConsumptionRecords' : IDL.Func(
        [],
        [IDL.Vec(ConsumptionRecord)],
        ['query'],
      ),
    'getUserConsumptionSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'records' : IDL.Vec(ConsumptionRecord),
            'totalUnits' : Units,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedTestConsumptionData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };