/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillDetails {
  'fixedCharges' : Rupees,
  'totalCost' : Rupees,
  'totalUnitsConsumed' : Units,
  'slabCosts' : Array<SlabBreakdown>,
}
export interface BillEstimate {
  'totalCost' : Rupees,
  'unitsConsumed' : Units,
  'unitCost' : bigint,
}
export interface ConsumptionRecord {
  'date' : Timestamp,
  'user' : UserId,
  'unitsConsumed' : Units,
  'timestamp' : Timestamp,
}
export type Rupees = bigint;
export interface SlabBreakdown {
  'cost' : Rupees,
  'name' : string,
  'units' : Units,
  'perUnitCost' : bigint,
}
export type Timestamp = bigint;
export type Units = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'consumerNumber' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addConsumptionRecord' : ActorMethod<[Timestamp, Units], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateBillEstimate' : ActorMethod<[Units, boolean], BillEstimate>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsumptionRecordsByUser' : ActorMethod<
    [UserId],
    Array<ConsumptionRecord>
  >,
  'getDetailedBillEstimate' : ActorMethod<[Units, boolean], BillDetails>,
  'getTotalUnitsConsumed' : ActorMethod<[UserId], Units>,
  'getUserConsumptionRecords' : ActorMethod<[], Array<ConsumptionRecord>>,
  'getUserConsumptionSummary' : ActorMethod<
    [],
    { 'records' : Array<ConsumptionRecord>, 'totalUnits' : Units }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedTestConsumptionData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];